/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.g39.reto5.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import utp.misiontic2022.c2.g39.reto5.controller.ControllerRequerimientos;
import utp.misiontic2022.c2.g39.reto5.model.vo.Requerimiento_2;

/**
 *
 * @author israelarbonaguerrero
 */
public class FrmRequerimientosBusqueda extends javax.swing.JFrame {

    /**
     * Creates new form FrmRequerimientosBusqueda
     */
    public FrmRequerimientosBusqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dcFecIni = new com.toedter.calendar.JDateChooser();
        dcFecFin = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tfCiudad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        miTablaB = new javax.swing.JTable();

        setTitle("I&M CONSTRUCTORA - BUSCADOR DE PROYECTOS");
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        bntBuscar.setText("Buscar ...");
        bntBuscar.setToolTipText("Pulse para iniciar la búsqueda ...");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Desde:");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dcFecIni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dcFecIni.setToolTipText("Seleccione la fecha inicial ...");

        dcFecFin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dcFecFin.setToolTipText("Seleccione la fecha final...");

        jLabel2.setText("Hasta:");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfCiudad.setToolTipText("Escriba el nombre de la ciudad ...");
        tfCiudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Ciudad:");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setToolTipText("<html>\n<p>Si existen proyectos iniciados dentro del intervalo de tiempo especificado entre <strong>Desde:</strong> y <strong>Hasta:</strong> </p>\n<p>y en la locación indicada en <strong>Ciudad:</strong> , en esta área se despliega una tabla de resultados mostrando</p>\n<p> la siguiente información relacionada con cada proyecto: «Fecha de Inicio», «Constructora», «Lider»,</p>\n<p>«Código del Tipo de Proyecto» y «Estrato». Si ningún proyecto cumple con los criteros de la búsqueda,</p>\n<p>la tabla se mostrará vacía.</p>\n</html>");

        miTablaB.setBackground(new java.awt.Color(192, 192, 192));
        miTablaB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miTablaB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        miTablaB.setToolTipText("En caso de existir proyectos iniciados dentro del intervalo de tiempo y en la ciudad que se especifican ... ");
        miTablaB.setOpaque(false);
        jScrollPane1.setViewportView(miTablaB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dcFecIni, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dcFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))))
                    .addComponent(bntBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcFecIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bntBuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fi = sdf.format(dcFecIni.getDate());
        String ff = sdf.format(dcFecFin.getDate());
      
        String[] columnNombre = {"Fec. Inicio","Ciudad","Constructora","Nom. Lider","Codigo Tipo","Estrato"};   
        ControllerRequerimientos controlador = new ControllerRequerimientos();
        ArrayList<Requerimiento_2> listaR2;
        
        try { 
            listaR2 = controlador.consultaRequerimiento_2(fi,ff,tfCiudad.getText());            
            Object[][] datos = new Object[listaR2.size()][6];
            
            int index = 0;
            for(Requerimiento_2 r: listaR2){
                datos[index][0] = r.getFecIni();
                datos[index][1] = r.getNombreCiudad();
                datos[index][2] = r.getNomConstructora();
                datos[index][3] = r.getNombreLider();
                datos[index][4] = r.getCodigoTipo();
                datos[index][5] = r.getEstrato();
                
                index++;
            }
            
            DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
            miTablaB.setModel(model);
            
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_bntBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRequerimientosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRequerimientosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRequerimientosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRequerimientosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRequerimientosBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private com.toedter.calendar.JDateChooser dcFecFin;
    private com.toedter.calendar.JDateChooser dcFecIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable miTablaB;
    private javax.swing.JTextField tfCiudad;
    // End of variables declaration//GEN-END:variables
}
